//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknoParrotUi.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeknoParrotUi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 By TeknoGods 的本地化字符串。
        /// </summary>
        public static string AboutCredits {
            get {
                return ResourceManager.GetString("AboutCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 游戏 的本地化字符串。
        /// </summary>
        public static string AddGame {
            get {
                return ResourceManager.GetString("AddGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 游戏 的本地化字符串。
        /// </summary>
        public static string DeleteGame {
            get {
                return ResourceManager.GetString("DeleteGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 下载 的本地化字符串。
        /// </summary>
        public static string DownloaderCancelled {
            get {
                return ResourceManager.GetString("DownloaderCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载 完成 的本地化字符串。
        /// </summary>
        public static string DownloaderComplete {
            get {
                return ResourceManager.GetString("DownloaderComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载中 的本地化字符串。
        /// </summary>
        public static string DownloaderDownloading {
            get {
                return ResourceManager.GetString("DownloaderDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载 出错 的本地化字符串。
        /// </summary>
        public static string DownloaderError {
            get {
                return ResourceManager.GetString("DownloaderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出错 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allowed range is 0-8191! 的本地化字符串。
        /// </summary>
        public static string ErrorAllowedRange {
            get {
                return ResourceManager.GetString("ErrorAllowedRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到TeknoParrotUI已在运行，是否要关闭它？ 的本地化字符串。
        /// </summary>
        public static string ErrorAlreadyRunning {
            get {
                return ResourceManager.GetString("ErrorAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot parse GUID: {0}. Please check that data has the GUID value only and nothing else! 的本地化字符串。
        /// </summary>
        public static string ErrorCannotParseGUID {
            get {
                return ResourceManager.GetString("ErrorCannotParseGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exception happened during loading ParrotData.xml! Generate new one by saving!
        ///
        ///{0} 的本地化字符串。
        /// </summary>
        public static string ErrorCantLoadParrotData {
            get {
                return ResourceManager.GetString("ErrorCantLoadParrotData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error loading {0}, Would you to delete it? 的本地化字符串。
        /// </summary>
        public static string ErrorCantLoadProfile {
            get {
                return ResourceManager.GetString("ErrorCantLoadProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exception happened during ParrotData.xml saving!
        ///
        ///{0} 的本地化字符串。
        /// </summary>
        public static string ErrorCantSaveParrotData {
            get {
                return ResourceManager.GetString("ErrorCantSaveParrotData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game location not set! Please set it in Game Settings. 的本地化字符串。
        /// </summary>
        public static string ErrorGamePathNotSet {
            get {
                return ResourceManager.GetString("ErrorGamePathNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Master server is offline. 的本地化字符串。
        /// </summary>
        public static string ErrorMasterServerOffline {
            get {
                return ResourceManager.GetString("ErrorMasterServerOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No (or invalid) APM3Id set in profile. APM3 games need these to work. Please click on the online Profile button to get yours and type it into the APM3Id field in the game settings. 的本地化字符串。
        /// </summary>
        public static string ErrorNoAPM3Id {
            get {
                return ResourceManager.GetString("ErrorNoAPM3Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your OnlineID is missing or wrong. Please put in your OnlineID from the website or else your game will get stuck on the Aime check on boot. Click on the Online Profile button to open up the website. 的本地化字符串。
        /// </summary>
        public static string ErrorNoOnlineId {
            get {
                return ResourceManager.GetString("ErrorNoOnlineId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seems you have extracted me to the directory of old TeknoParrot. Please extract me to a new directory instead! 的本地化字符串。
        /// </summary>
        public static string ErrorOldTeknoParrotDirectory {
            get {
                return ResourceManager.GetString("ErrorOldTeknoParrotDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seems like this is first time you are running TeknoParrotUi, please set emulation settings. 的本地化字符串。
        /// </summary>
        public static string FirstRun {
            get {
                return ResourceManager.GetString("FirstRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏列表: 的本地化字符串。
        /// </summary>
        public static string GameList {
            get {
                return ResourceManager.GetString("GameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏 运行中 的本地化字符串。
        /// </summary>
        public static string GameRunning {
            get {
                return ResourceManager.GetString("GameRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 由于您强制关闭了模拟器，请检查任务管理器中是否仍有与模拟器或游戏相关的进程在运行 的本地化字符串。
        /// </summary>
        public static string GameRunningCheckTaskMgr {
            get {
                return ResourceManager.GetString("GameRunningCheckTaskMgr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强制 退出游戏 的本地化字符串。
        /// </summary>
        public static string GameRunningForceQuit {
            get {
                return ResourceManager.GetString("GameRunningForceQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏 已停止 的本地化字符串。
        /// </summary>
        public static string GameRunningGameStopped {
            get {
                return ResourceManager.GetString("GameRunningGameStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏 可执行文件 的本地化字符串。
        /// </summary>
        public static string GameSettingsGameExecutable {
            get {
                return ResourceManager.GetString("GameSettingsGameExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏 可执行文件 的本地化字符串。
        /// </summary>
        public static string GameSettingsGameExecutableFilter {
            get {
                return ResourceManager.GetString("GameSettingsGameExecutableFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择游戏目录的可执行文件 的本地化字符串。
        /// </summary>
        public static string GameSettingsSelectGameExecutable {
            get {
                return ResourceManager.GetString("GameSettingsSelectGameExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此游戏为64位版本，无法在32位操作系统上运行。 的本地化字符串。
        /// </summary>
        public static string Library64bit {
            get {
                return ResourceManager.GetString("Library64bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到您有其他模拟器已在运行，请从游戏目录中删除以下文件： 的本地化字符串。
        /// </summary>
        public static string LibraryAnotherEmulator {
            get {
                return ResourceManager.GetString("LibraryAnotherEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请立即更新OpenParrot！检测到您正在使用非官方的{0}文件！游戏可能崩溃或运行不稳定。是否继续？ 的本地化字符串。
        /// </summary>
        public static string LibraryBadiDMAC {
            get {
                return ResourceManager.GetString("LibraryBadiDMAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot find game exe at: {0} 的本地化字符串。
        /// </summary>
        public static string LibraryCantFindGame {
            get {
                return ResourceManager.GetString("LibraryCantFindGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot find {0}!
        ///It is probably removed by your anti-virus software.
        ///Please re-extract TeknoParrot. 的本地化字符串。
        /// </summary>
        public static string LibraryCantFindLoader {
            get {
                return ResourceManager.GetString("LibraryCantFindLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制器 设置 的本地化字符串。
        /// </summary>
        public static string LibraryControllerSetup {
            get {
                return ResourceManager.GetString("LibraryControllerSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 选中游戏 的本地化字符串。
        /// </summary>
        public static string LibraryDeleteGame {
            get {
                return ResourceManager.GetString("LibraryDeleteGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This will download every missing icon for TeknoParrot. The file is around 50 megabytes. Are you sure you want to continue? 的本地化字符串。
        /// </summary>
        public static string LibraryDownloadAllIcons {
            get {
                return ResourceManager.GetString("LibraryDownloadAllIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载 缺失的游戏图标 的本地化字符串。
        /// </summary>
        public static string LibraryDownloadMissingIcons {
            get {
                return ResourceManager.GetString("LibraryDownloadMissingIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Emulator 的本地化字符串。
        /// </summary>
        public static string LibraryEmulator {
            get {
                return ResourceManager.GetString("LibraryEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Second game location not set! Please set it in Game Settings. 的本地化字符串。
        /// </summary>
        public static string LibraryGameLocation2NotSet {
            get {
                return ResourceManager.GetString("LibraryGameLocation2NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game location not set! Please set it in Game Settings. 的本地化字符串。
        /// </summary>
        public static string LibraryGameLocationNotSet {
            get {
                return ResourceManager.GetString("LibraryGameLocationNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏 设置 的本地化字符串。
        /// </summary>
        public static string LibraryGameSettings {
            get {
                return ResourceManager.GetString("LibraryGameSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are possibly some invalid files in your game directory.
        ///The following files may need to be removed from the game directory, unless you know what they are:
        ///   的本地化字符串。
        /// </summary>
        public static string LibraryInvalidFiles {
            get {
                return ResourceManager.GetString("LibraryInvalidFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click Yes to continue running the game as is. 的本地化字符串。
        /// </summary>
        public static string LibraryInvalidFilesContinue {
            get {
                return ResourceManager.GetString("LibraryInvalidFilesContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动 游戏 的本地化字符串。
        /// </summary>
        public static string LibraryLaunchGame {
            get {
                return ResourceManager.GetString("LibraryLaunchGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 百科 的本地化字符串。
        /// </summary>
        public static string LibraryMoreInfo {
            get {
                return ResourceManager.GetString("LibraryMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seems like you are not running TeknoParrotUI as Administrator! The game {0} requires the UI to be running as Administrator to function properly. Continue anyway WITHOUT admin rights? This might cause issues or crashes. 的本地化字符串。
        /// </summary>
        public static string LibraryNeedsAdmin {
            get {
                return ResourceManager.GetString("LibraryNeedsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have no games set up. Do you want to add one now? 的本地化字符串。
        /// </summary>
        public static string LibraryNoGames {
            get {
                return ResourceManager.GetString("LibraryNoGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It appears that you are trying to verify a game that doesn&apos;t have a clean file hash list yet. 的本地化字符串。
        /// </summary>
        public static string LibraryNoHashes {
            get {
                return ResourceManager.GetString("LibraryNoHashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Game Information Available 的本地化字符串。
        /// </summary>
        public static string LibraryNoInfo {
            get {
                return ResourceManager.GetString("LibraryNoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线上 档案 的本地化字符串。
        /// </summary>
        public static string LibraryOnlineProfile {
            get {
                return ResourceManager.GetString("LibraryOnlineProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络 联线 的本地化字符串。
        /// </summary>
        public static string LibraryPlayOnline {
            get {
                return ResourceManager.GetString("LibraryPlayOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机台 测试菜单 的本地化字符串。
        /// </summary>
        public static string LibraryTestMenu {
            get {
                return ResourceManager.GetString("LibraryTestMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle test mode. 的本地化字符串。
        /// </summary>
        public static string LibraryToggleTestMode {
            get {
                return ResourceManager.GetString("LibraryToggleTestMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证 游戏完整性 的本地化字符串。
        /// </summary>
        public static string LibraryVerifyGame {
            get {
                return ResourceManager.GetString("LibraryVerifyGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string MainAbout {
            get {
                return ResourceManager.GetString("MainAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure? 的本地化字符串。
        /// </summary>
        public static string MainAreYouSure {
            get {
                return ResourceManager.GetString("MainAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动检查更新 的本地化字符串。
        /// </summary>
        public static string MainCheckUpdates {
            get {
                return ResourceManager.GetString("MainCheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载 游戏图标 的本地化字符串。
        /// </summary>
        public static string MainDownloadMissingIcons {
            get {
                return ResourceManager.GetString("MainDownloadMissingIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地游戏库 的本地化字符串。
        /// </summary>
        public static string MainLibrary {
            get {
                return ResourceManager.GetString("MainLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出程序 的本地化字符串。
        /// </summary>
        public static string MainQuit {
            get {
                return ResourceManager.GetString("MainQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏 扫描 的本地化字符串。
        /// </summary>
        public static string MainRomScanner {
            get {
                return ResourceManager.GetString("MainRomScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string MainSettings {
            get {
                return ResourceManager.GetString("MainSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TP Online (OLD) 的本地化字符串。
        /// </summary>
        public static string MainTPOnline {
            get {
                return ResourceManager.GetString("MainTPOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线 联机 的本地化字符串。
        /// </summary>
        public static string MainTPOnlineNew {
            get {
                return ResourceManager.GetString("MainTPOnlineNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Become A Subscriber! 的本地化字符串。
        /// </summary>
        public static string PatreonBecomeAPatron {
            get {
                return ResourceManager.GetString("PatreonBecomeAPatron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeRegister Key 的本地化字符串。
        /// </summary>
        public static string PatreonDeregisterKey {
            get {
                return ResourceManager.GetString("PatreonDeregisterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error from other process: 的本地化字符串。
        /// </summary>
        public static string PatreonError {
            get {
                return ResourceManager.GetString("PatreonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This feature requires TeknoParrot Core, please install it. 的本地化字符串。
        /// </summary>
        public static string PatreonMissingBudgie {
            get {
                return ResourceManager.GetString("PatreonMissingBudgie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subscription key must not be blank 的本地化字符串。
        /// </summary>
        public static string PatreonMustNotBeBlank {
            get {
                return ResourceManager.GetString("PatreonMustNotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register Key 的本地化字符串。
        /// </summary>
        public static string PatreonRegisterKey {
            get {
                return ResourceManager.GetString("PatreonRegisterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status: 的本地化字符串。
        /// </summary>
        public static string PatreonStatus {
            get {
                return ResourceManager.GetString("PatreonStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check for updates on launch 的本地化字符串。
        /// </summary>
        public static string SettingsCheckForUpdates {
            get {
                return ResourceManager.GetString("SettingsCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Common Settings 的本地化字符串。
        /// </summary>
        public static string SettingsCommon {
            get {
                return ResourceManager.GetString("SettingsCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirmation prompt on exit 的本地化字符串。
        /// </summary>
        public static string SettingsConfirmExit {
            get {
                return ResourceManager.GetString("SettingsConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Direct Input Wheel Settings 的本地化字符串。
        /// </summary>
        public static string SettingsDInputWheel {
            get {
                return ResourceManager.GetString("SettingsDInputWheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Force Feedback Plugin 的本地化字符串。
        /// </summary>
        public static string SettingsDownloadFFB {
            get {
                return ResourceManager.GetString("SettingsDownloadFFB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download game icon when selected 的本地化字符串。
        /// </summary>
        public static string SettingsDownloadIcon {
            get {
                return ResourceManager.GetString("SettingsDownloadIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log output to file 的本地化字符串。
        /// </summary>
        public static string SettingsElf2LogToFile {
            get {
                return ResourceManager.GetString("SettingsElf2LogToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Elfldr2 Settings 的本地化字符串。
        /// </summary>
        public static string SettingsElfldr2 {
            get {
                return ResourceManager.GetString("SettingsElfldr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network Adapter 的本地化字符串。
        /// </summary>
        public static string SettingsElfldr2NetworkAdapter {
            get {
                return ResourceManager.GetString("SettingsElfldr2NetworkAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full Axis Brake 的本地化字符串。
        /// </summary>
        public static string SettingsFullBrake {
            get {
                return ResourceManager.GetString("SettingsFullBrake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full Axis Gas 的本地化字符串。
        /// </summary>
        public static string SettingsFullGas {
            get {
                return ResourceManager.GetString("SettingsFullGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable Hardware Acceleration in UI 的本地化字符串。
        /// </summary>
        public static string SettingsHardwareAccel {
            get {
                return ResourceManager.GetString("SettingsHardwareAccel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide console windows 的本地化字符串。
        /// </summary>
        public static string SettingsHideConsoleWindows {
            get {
                return ResourceManager.GetString("SettingsHideConsoleWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable Vanguard Warning 的本地化字符串。
        /// </summary>
        public static string SettingsHideVanguardWarning {
            get {
                return ResourceManager.GetString("SettingsHideVanguardWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Joystick Gun Settings 的本地化字符串。
        /// </summary>
        public static string SettingsJoystickGunSettings {
            get {
                return ResourceManager.GetString("SettingsJoystickGunSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load last game played on launch 的本地化字符串。
        /// </summary>
        public static string SettingsLoadLastPlayed {
            get {
                return ResourceManager.GetString("SettingsLoadLastPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player 1 Gun Joystick Sensitivity 的本地化字符串。
        /// </summary>
        public static string SettingsP1GunJoystickSensitivity {
            get {
                return ResourceManager.GetString("SettingsP1GunJoystickSensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player 2 Gun Joystick Sensitivity 的本地化字符串。
        /// </summary>
        public static string SettingsP2GunJoystickSensitivity {
            get {
                return ResourceManager.GetString("SettingsP2GunJoystickSensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reverse Axis Brake 的本地化字符串。
        /// </summary>
        public static string SettingsReverseBrake {
            get {
                return ResourceManager.GetString("SettingsReverseBrake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reverse Axis Gas 的本地化字符串。
        /// </summary>
        public static string SettingsReverseGas {
            get {
                return ResourceManager.GetString("SettingsReverseGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 设置 的本地化字符串。
        /// </summary>
        public static string SettingsSaveSettings {
            get {
                return ResourceManager.GetString("SettingsSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show current game playing on Discord 的本地化字符串。
        /// </summary>
        public static string SettingsShowGameOnDiscord {
            get {
                return ResourceManager.GetString("SettingsShowGameOnDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable sTo0z Zone 的本地化字符串。
        /// </summary>
        public static string SettingsSto0zZone {
            get {
                return ResourceManager.GetString("SettingsSto0zZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sto0z Zone 的本地化字符串。
        /// </summary>
        public static string SettingsSto0zZoneTitle {
            get {
                return ResourceManager.GetString("SettingsSto0zZoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本 颜色 的本地化字符串。
        /// </summary>
        public static string SettingsUIColour {
            get {
                return ResourceManager.GetString("SettingsUIColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UI Customization (Patreon) 的本地化字符串。
        /// </summary>
        public static string SettingsUICustomization {
            get {
                return ResourceManager.GetString("SettingsUICustomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深色 主题 的本地化字符串。
        /// </summary>
        public static string SettingsUIDarkMode {
            get {
                return ResourceManager.GetString("SettingsUIDarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use a different theme on holidays 的本地化字符串。
        /// </summary>
        public static string SettingsUIHolidayThemes {
            get {
                return ResourceManager.GetString("SettingsUIHolidayThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 成功 {0}! 的本地化字符串。
        /// </summary>
        public static string SuccessfullySaved {
            get {
                return ResourceManager.GetString("SuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Lobby and Launch Game 的本地化字符串。
        /// </summary>
        public static string TPOCreateLobby {
            get {
                return ResourceManager.GetString("TPOCreateLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter by game: 的本地化字符串。
        /// </summary>
        public static string TPOFilter {
            get {
                return ResourceManager.GetString("TPOFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏 的本地化字符串。
        /// </summary>
        public static string TPOGame {
            get {
                return ResourceManager.GetString("TPOGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Join Lobby and Launch Game 的本地化字符串。
        /// </summary>
        public static string TPOJoinLobby {
            get {
                return ResourceManager.GetString("TPOJoinLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lobby Name 的本地化字符串。
        /// </summary>
        public static string TPOLobbyName {
            get {
                return ResourceManager.GetString("TPOLobbyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家 的本地化字符串。
        /// </summary>
        public static string TPOPlayers {
            get {
                return ResourceManager.GetString("TPOPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh Lobbies 的本地化字符串。
        /// </summary>
        public static string TPORefresh {
            get {
                return ResourceManager.GetString("TPORefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现程序有更新 的本地化字符串。
        /// </summary>
        public static string UpdaterAvailable {
            get {
                return ResourceManager.GetString("UpdaterAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有 安装 的本地化字符串。
        /// </summary>
        public static string UpdaterNotInstalled {
            get {
                return ResourceManager.GetString("UpdaterNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Changelog 的本地化字符串。
        /// </summary>
        public static string UpdaterOpenChangelog {
            get {
                return ResourceManager.GetString("UpdaterOpenChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否让TeknoParrotUi重新启动以完成更新？若选择否，程序将直接关闭。 的本地化字符串。
        /// </summary>
        public static string UpdaterRestart {
            get {
                return ResourceManager.GetString("UpdaterRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sucessfully updated {0} to {1} 的本地化字符串。
        /// </summary>
        public static string UpdaterSuccess {
            get {
                return ResourceManager.GetString("UpdaterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        public static string UpdaterUpdate {
            get {
                return ResourceManager.GetString("UpdaterUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TeknoParrot检测到您当前正在运行《VALORANT》的反作弊系统Riot Vanguard。Vanguard会干扰TeknoParrot加载游戏，并可能导致运行异常！ 的本地化字符串。
        /// </summary>
        public static string VanguardDetected {
            get {
                return ResourceManager.GetString("VanguardDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证 已取消 的本地化字符串。
        /// </summary>
        public static string VerifyCancelled {
            get {
                return ResourceManager.GetString("VerifyCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在验证游戏文件完整性…… 的本地化字符串。
        /// </summary>
        public static string VerifyChecking {
            get {
                return ResourceManager.GetString("VerifyChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏文件校验 失败 的本地化字符串。
        /// </summary>
        public static string VerifyFilesInvalid {
            get {
                return ResourceManager.GetString("VerifyFilesInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到游戏文件异常，可能原因包括：下载不完整/文件损坏，游戏镜像转储错误，病毒感染导致文件篡改，安装了非官方修改补丁（如分辨率补丁、英文汉化补丁等）。 的本地化字符串。
        /// </summary>
        public static string VerifyFilesInvalidExplain {
            get {
                return ResourceManager.GetString("VerifyFilesInvalidExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏文件 校验 的本地化字符串。
        /// </summary>
        public static string VerifyFilesValid {
            get {
                return ResourceManager.GetString("VerifyFilesValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid: 的本地化字符串。
        /// </summary>
        public static string VerifyInvalid {
            get {
                return ResourceManager.GetString("VerifyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Valid: 的本地化字符串。
        /// </summary>
        public static string VerifyValid {
            get {
                return ResourceManager.GetString("VerifyValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
